name: tf_ner
dependencies:
  #
  # Basics
  - python=3.7
  - matplotlib
  - gast=0.2.2
  - packaging
  - tqdm
  - pip
  #
  # Deep learning
  - pip:
    - tensorflow==1.14.0
    - git+https://github.com/guillaumegenthial/tf_metrics.git
    - -e .
  #
  # Misc
  - jupyter
  - neovim
